kind: Service
apiVersion: v1
metadata:
  namespace: olivier-dev
  name: olivier-service
  labels:
    app: olivier
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: olivier