apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: manhattan-trigger
  namespace: manhattan-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: manhattan
  template:
    ref: manhattan