kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: manhattan-dev
  name: manhattan-route
  labels:
    app: manhattan
spec:
  to:
    kind: Service
    name: manhattan-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
