kind: Service
apiVersion: v1
metadata:
  namespace: devops
  name: exporter-service
  labels:
    app: exporter
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: exporter