kind: Secret
apiVersion: v1
metadata:
  name: bootstraper-secret-0
  labels:
    app: bootstraper
    app.kubernetes.io/instance: bootstraper
data:
  actuator.password: c3lzdGVtcGFzc3dvcmQ=
  argo.password: SVlrbjdDRThVTGdGY01ocGVQUnh1U3FEd3kyMTZ2WlQ=
  codeready.client.secret: ZDY1YmM4OWItODBhYS00ZmJiLWJjNjctYjhhMWZkMzMwMzE1
  codeready.user.password: T3BleGlhMjYyKg==
  git.password: Z2hwXzlGcG5YVEJsVkQ1a3dVaW5BNHN4cUYwdkxFOXI1ZTNBSVRhYQ==
type: Opaque
