kind: Service
apiVersion: v1
metadata:
  namespace: test-create-pvc-dev
  name: test-create-pvc-service
  labels:
    app: test-create-pvc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: test-create-pvc