kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: {{ocp-namespace}}
  name: gitops-importer-route
  labels:
    app: gitops-importer
spec:
  to:
    kind: Service
    name: gitops-importer-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
