kind: Service
apiVersion: v1
metadata:
  namespace: gitops-importer-dev
  name: gitops-importer-service
  labels:
    app: gitops-importer
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: gitops-importer