apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: test-eliott-trigger
  namespace: test-eliott-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: test-eliott
  template:
    ref: test-eliott