kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: test-eliott-dev
  name: test-eliott-route
  labels:
    app: test-eliott
spec:
  to:
    kind: Service
    name: test-eliott-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
