apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: boston-trigger
  namespace: boston-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: boston
  template:
    ref: boston