kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: chicago-dev
  annotations:
    reloader.stakater.com/auto: "true"
    build-commit: '@git.commit.id.abbrev@'
    build-date: "@git.build.time@"
  name: chicago
  labels:
    app: chicago
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chicago
  template:
    metadata:
      name: chicago
      labels:
        app: chicago
      annotations:
        build-commit: '@git.commit.id.abbrev@'
        build-date: "@git.build.time@"
    spec:
      volumes:
        - name: emptydirlogs
          emptyDir: {}
      containers:
        - name: microservice-pod 
          resources:
            requests:
              memory: 250Mi
              cpu : 200m
            limits:
              memory: 750Mi
              cpu : 500m
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8080
              scheme: HTTP
          env:
            - name: welcome.message
              valueFrom:
                configMapKeyRef:
                  name: chicago-cm-0
                  key: welcome.message
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          imagePullPolicy: Always
          volumeMounts:
            - name: emptydirlogs
              mountPath: /Logs
          image: >-
            image-registry.openshift-image-registry.svc.cluster.local:5000/chicago-dev/chicago:latest
      restartPolicy: Always