kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: chicago-dev
  name: chicago-route
  labels:
    app: chicago
spec:
  to:
    kind: Service
    name: chicago-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
