kind: Service
apiVersion: v1
metadata:
  namespace: chicago-dev
  name: chicago-service
  labels:
    app: chicago
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: chicago