apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: test-owen-trigger
  namespace: test-owen-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: test-owen
  template:
    ref: test-owen