kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: new-york-dev
  annotations:
    build-commit: '@git.commit.id.abbrev@'
    build-date: "@git.build.time@"
  name: new-york
  labels:
    app: new-york
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-york
  template:
    metadata:
      name: new-york
      labels:
        app: new-york
      annotations:
        build-commit: '@git.commit.id.abbrev@'
        build-date: "@git.build.time@"
    spec:
      volumes:
        - name: emptydirlogs
          emptyDir: {}
      containers:
        - name: microservice-pod 
          resources:
            requests:
              memory: 250Mi
              cpu : 200m
            limits:
              memory: 750Mi
              cpu : 500m
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8080
              scheme: HTTP
          env:
            - name: welcome.message
              valueFrom:
                configMapKeyRef:
                  name: new-york-cm-0
                  key: welcome.message
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          imagePullPolicy: Always
          volumeMounts:
            - name: emptydirlogs
              mountPath: /Logs
          image: >-
            image-registry.openshift-image-registry.svc.cluster.local:5000/new-york-dev/new-york:latest
      restartPolicy: Always