kind: ConfigMap
apiVersion: v1
metadata:
  namespace: placeholdermanager-dev
  name: placeholdermanager-cm-0
  labels:
    app: placeholdermanager
data:
  cluster-suffix: "apps.ocp-lab.its4u.eu"
  ocp.environment: "dev"
  ocp.replicas: "1"
  ocp-cluster.registry: "image-registry.openshift-image-registry.svc.cluster.local:5000"
  ocp-namespace: "placeholdermanager-dev"
  app-name: "OCP - GitOps Application Deployer v2"
  git.user: "openshift"
  argo.user: "admin"
---
