kind: Secret
apiVersion: v1
metadata:
  namespace: placeholdermanager-dev
  name: placeholdermanager-secret-0
  labels:
    app: placeholdermanager    
data:
  actuator.password: "password"
  git.password: "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"
type: Opaque
---
 