kind: ConfigMap
apiVersion: v1
metadata:
  namespace: memory-leak-dev
  name: memory-leak-cm-0
  labels:
    app: memory-leak
data: 
  app-limit.memory: "300Mi"
  ocp-cluster.registry: "image-registry.openshift-image-registry.svc.cluster.local:5000"
  app-limit.cpu: "500m"
  ocp.environment: "dev"
  ocp-namespace: "memory-leak-dev"
  cluster-suffix: "apps.ocp-lab.its4u.eu"
  app-actuator.port: "8080"
  app-request.memory: "100Mi"
  app-container.port: "8080"
  app-request.cpu: "200m"
  ocp.replicas: "1"
  app-version: "0.0.1-SNAPSHOT"
---
