kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: {{ocp-namespace}}
  name: memory-leak-route
  labels:
    app: memory-leak
spec:
  to:
    kind: Service
    name: memory-leak-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
