kind: Secret
apiVersion: v1
metadata:
  namespace: {{ocp-namespace}}
  name: memory-leak-secret-0
  labels:
    app: memory-leak    
stringData:  
  actuator.password: {{actuator.password}}
type: Opaque
---
 