kind: Service
apiVersion: v1
metadata:
  namespace: memory-leak-dev
  name: memory-leak-service
  labels:
    app: memory-leak
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: memory-leak