kind: Service
apiVersion: v1
metadata:
  namespace: bankaccount-dev
  name: bankaccount-service
  labels:
    app: bankaccount
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: bankaccount