apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: multi-env-trigger
  namespace: multi-env-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: multi-env
  template:
    ref: multi-env