kind: ConfigMap
apiVersion: v1
metadata:
  namespace: multi-env-dev
  name: multi-env-cm-0
  labels:
    app: multi-env
data: 
  ocp-cluster.registry: "{{ocp-cluster.registry}}"
  ocp.environment: "{{ocp.environment}}"
  ocp-namespace: "{{ocp-namespace}}"
  cluster-suffix: "{{cluster-suffix}}"
  ocp.replicas: "{{ocp.replicas}}"
  app-version: "{{app-version}}"
---
