kind: Service
apiVersion: v1
metadata:
  namespace: multi-env-dev
  name: multi-env-service
  labels:
    app: multi-env
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: multi-env