apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: surprise-trigger
  namespace: surprise-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: surprise
  template:
    ref: surprise