kind: Service
apiVersion: v1
metadata:
  namespace: surprise-dev
  name: surprise-service
  labels:
    app: surprise
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: surprise