kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: visioner-dev
  name: visioner-route
  labels:
    app: visioner
spec:
  to:
    kind: Service
    name: visioner-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
