kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: argo4u-dev
  name: argo4u-route
  labels:
    app: argo4u
spec:
  to:
    kind: Service
    name: argo4u-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
