kind: Service
apiVersion: v1
metadata:
  namespace: appolo-dev
  name: appolo-service
  labels:
    app: appolo
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: appolo