apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: migrator
  name: el-migrator
  namespace: migrator-dev
spec:
  host: el-migrator-migrator-dev.apps.ocp-lab.its4u.eu
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-migrator
    weight: 100
  wildcardPolicy: None