kind: ConfigMap
apiVersion: v1
metadata:
  namespace: devops
  name: migrator-cm-0
  labels:
    app: migrator
data: 
  app-limit.memory: "750Mi"
  ocp-cluster.registry: "image-registry.openshift-image-registry.svc.cluster.local:5000"
  app-limit.cpu: "500m"
  ocp.environment: "dev"
  ocp-namespace: "devops"
  cluster-suffix: "apps.ocp-lab.its4u.eu"
  app-actuator.port: "8080"
  app-request.memory: "250Mi"
  app-container.port: "8080"
  app-request.cpu: "200m"
  ocp.replicas: "1"
  app-version: "v2.0-SNAPSHOT"
---
