kind: Service
apiVersion: v1
metadata:
  namespace: volvo-dev
  name: volvo-service
  labels:
    app: volvo
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: volvo