kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: test-ksc-dev
  annotations:
    its4u.placeholders/auto: "true"
    reloader.stakater.com/auto: "true"
    build-commit: '@git.commit.id.abbrev@'
    build-date: "@git.build.time@"
  name: test-ksc
  labels:
    app: test-ksc
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test-ksc
  template:
    metadata:
      name: test-ksc
      labels:
        app: test-ksc
      annotations:
        build-commit: '@git.commit.id.abbrev@'
        build-date: "@git.build.time@"
    spec:
      volumes:
        - name: emptydirlogs
          emptyDir: {}
      containers:
        - name: microservice-pod 
          resources:
            requests:
              memory: 250Mi
              cpu : 200m
            limits:
              memory: 750Mi
              cpu : 500m
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8080
              scheme: HTTP
          env:
            - name: cluster-suffix
              valueFrom:
                configMapKeyRef:
                  name: test-ksc-cm-0
                  key: cluster-suffix
            - name: ocp.environment
              valueFrom:
                configMapKeyRef:
                  name: test-ksc-cm-0
                  key: ocp.environment
            - name: ocp.replicas
              valueFrom:
                configMapKeyRef:
                  name: test-ksc-cm-0
                  key: ocp.replicas
            - name: ocp-cluster.registry
              valueFrom:
                configMapKeyRef:
                  name: test-ksc-cm-0
                  key: ocp-cluster.registry
            - name: ocp-namespace
              valueFrom:
                configMapKeyRef:
                  name: test-ksc-cm-0
                  key: ocp-namespace
            - name: actuator.password
              valueFrom:
                secretKeyRef:
                  name: test-ksc-secret-0
                  key: actuator.password
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          imagePullPolicy: Always
          volumeMounts:
            - name: emptydirlogs
              mountPath: /Logs
          image: >-
            image-registry.openshift-image-registry.svc.cluster.local:5000/test-ksc-dev/test-ksc:latest
      restartPolicy: Always