apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: porsche-trigger
  namespace: porsche-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: porsche
  template:
    ref: porsche