apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: capacitytool
  namespace: capacitytool-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: capacitytool-trigger