kind: Service
apiVersion: v1
metadata:
  namespace: capacitytool-dev
  name: capacitytool-service
  labels:
    app: capacitytool
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: capacitytool