kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netscape-pipeline-claim
  namespace: {{ocp-namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
status:

