apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: peugeot-trigger
  namespace: peugeot-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: peugeot
  template:
    ref: peugeot