kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: peugeot-dev
  name: peugeot-route
  labels:
    app: peugeot
spec:
  to:
    kind: Service
    name: peugeot-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
