apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miami
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: miami/jkube/
    repoURL: https://github.com/kevbrain/ocp-gitops-apps-deploy.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true