kind: ConfigMap
apiVersion: v1
metadata:
  namespace: capacity-tool-dev
  name: capacity-tool-cm-0
  labels:
    app: capacity-tool
data: 
  its4u.environment: "dev"
  alert.percentage.consumption.resource.threshold: "90"
  app.ocp.instance.name: "lab.its4u"
  app.ocp.console.url: "https://console-openshift-console.apps.ocp-lab.its4u.eu/"
  app.envs: "dev:1,tst:2,int:2,prd:2"
  app.envs.namespace.label: "its4u.com/env"
  app.mail.default.recipient: "kevyn.schrondweiler@its4u.com"
  app.mail.smtp.host: "smtp.host"
  app.mail.smtp.port: "25"
  app.mail.user: "usermail"
  app.ocp.server.url: "https://api.ocp-lab.its4u.eu:6443"
  app.simulator.reserve.pods: "20"
  app.gonogo.block.request.level: "90"
  app.gonogo.warning.request.level: "80"
  app-limit.memory: "750Mi"
  app-limit.cpu: "500m"
  ocp.environment: "dev"
  ocp-namespace: "capacity-tool-dev"
  ocp.replicas: "1"
  ocp-cluster.registry: "image-registry.openshift-image-registry.svc.cluster.local:5000"
  cluster-suffix: "apps.ocp-lab.its4u.eu"
  app-actuator.port: "8080"
  app-request.memory: "250Mi"
  app-container.port: "8080"
  app-request.cpu: "200m"
  app-version: "0.0.1-SNAPSHOT"
  prometheus.query.maxovertime: "2d"
  prometheus.url: "https://prometheus-k8s-openshift-monitoring.apps.ocp-lab.its4u.eu"
---
