kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: capacity-tool-dev
  annotations:
    its4u.placeholders/auto: "true"
    reloader.stakater.com/auto: "true"
  name: capacity-tool
  labels:
    app: capacity-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capacity-tool
  template:
    metadata:
      name: capacity-tool
      labels:
        app: capacity-tool
    spec:
      volumes:
        - name: emptydirlogs
          emptyDir: {}
      containers:
        - name: microservice-pod 
          resources:
            requests:
              memory: 250Mi
              cpu : 200m
            limits:
              memory: 750Mi
              cpu : 500m
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8080
              scheme: HTTP
          env:
            - name: app-limit.memory
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app-limit.memory
            - name: ocp-cluster.registry
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: ocp-cluster.registry
            - name: app-limit.cpu
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app-limit.cpu
            - name: ocp.environment
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: ocp.environment
            - name: ocp-namespace
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: ocp-namespace
            - name: cluster-suffix
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: cluster-suffix
            - name: app-actuator.port
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app-actuator.port
            - name: app-request.memory
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app-request.memory
            - name: app-container.port
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app-container.port
            - name: app-request.cpu
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app-request.cpu
            - name: ocp.replicas
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: ocp.replicas
            - name: app-version
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app-version
            - name: alert.percentage.consumption.resource.threshold
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: alert.percentage.consumption.resource.threshold
            - name: app.envs
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app.envs
            - name: app.envs.namespace.label
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app.envs.namespace.label
            - name: app.gonogo.block.request.level
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app.gonogo.block.request.level
            - name: app.gonogo.warning.request.level
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app.gonogo.warning.request.level
            - name: app.mail.default.recipient
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app.mail.default.recipient
            - name: app.mail.smtp.host
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app.mail.smtp.host
            - name: app.mail.smtp.port
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app.mail.smtp.port
            - name: app.mail.user
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app.mail.user
            - name: app.ocp.instance.name
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app.ocp.instance.name
            - name: app.ocp.server.url
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app.ocp.server.url
            - name: app.simulator.reserve.pods
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app.simulator.reserve.pods
            - name: project.default.limit.cpu
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: project.default.limit.cpu
            - name: project.default.limit.memory
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: project.default.limit.memory
            - name: project.default.request.cpu
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: project.default.request.cpu
            - name: project.default.request.memory
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: project.default.request.memory
            - name: prometheus.query.maxovertime
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: prometheus.query.maxovertime
            - name: app.ocp.console.url
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: app.ocp.console.url
            - name: prometheus.url
              valueFrom:
                configMapKeyRef:
                  name: capacity-tool-cm-0
                  key: prometheus.url
            - name: actuator.password
              valueFrom:
                secretKeyRef:
                  name: capacity-tool-secret-0
                  key: actuator.password
            - name: app.mail.password
              valueFrom:
                secretKeyRef:
                  name: capacity-tool-secret-0
                  key: app.mail.password
            - name: app.ocp.server.token
              valueFrom:
                secretKeyRef:
                  name: capacity-tool-secret-0
                  key: app.ocp.server.token
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          imagePullPolicy: Always
          volumeMounts:
            - name: emptydirlogs
              mountPath: /Logs
          image: >-
            image-registry.openshift-image-registry.svc.cluster.local:5000/capacity-tool-dev/capacity-tool:0.0.1-SNAPSHOT
      restartPolicy: Always