kind: Secret
apiVersion: v1
metadata:
  namespace: capacity-tool-dev
  name: capacity-tool-secret-0
  labels:
    app: capacity-tool    
stringData:  
  actuator.password: password
  app.mail.password: password
  app.ocp.server.token: {{app.ocp.server.token}}
type: Opaque
---
 