apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: test-toto
  name: el-test-toto
  namespace: test-toto-dev
spec:
  host: el-test-toto-test-toto-dev.apps.ocp-lab.its4u.eu
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-test-toto
    weight: 100
  wildcardPolicy: None