apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: lab-devops-dev-trigger
  namespace: lab-devops-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: lab-devops-dev-triggerBinging
  template:
    ref: lab-devops-dev-triggerTemplate