apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: lab-devops-dev-triggerTemplate
  namespace: lab-devops-dev
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
  - name: git-repo-name
    description: The name of the deployment to be created / patched
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-deploy-$(tt.params.git-repo-name)-$(tt.params.git-revision)
      namespace: lab-devops-dev
      generation: 1
    spec:
      pipelineRef:
        name: lab-devops-dev-pipeline-build
      serviceAccountName: pipeline
      timeout: 1h0m0s
      workspaces:
        - name: source
          persistentVolumeClaim:
            claimName: lab-devops-dev-pipeline-claim
        - configMap:
            name: maven-settings-cm
          name: maven-settings
