kind: ConfigMap
apiVersion: v1
metadata:
  namespace: lab-devops-dev
  name: lab-devops-cm-0
  labels:
    app: lab-devops
data: 
  app-limit.memory: "750Mi"
  ocp-cluster.registry: "image-registry.openshift-image-registry.svc.cluster.local:5000"
  app-limit.cpu: "500m"
  ocp.environment: "dev"
  ocp-namespace: "lab-devops-dev"
  cluster-suffix: "apps.ocp-lab.its4u.eu"
  app-actuator.port: "8080"
  app-request.memory: "250Mi"
  app-container.port: "8080"
  app-request.cpu: "200m"
  ocp.replicas: "1"
  app-version: "0.0.1-SNAPSHOT"
---
