kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: {{ocp-namespace}}
  name: lab-devops-route
  labels:
    app: lab-devops
spec:
  to:
    kind: Service
    name: lab-devops-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
