kind: Service
apiVersion: v1
metadata:
  namespace: erp-api-dev
  name: erp-api-service
  labels:
    app: erp-api
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: erp-api