kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: todelete-dev
  annotations:
    its4u.placeholders/auto: "true"
    reloader.stakater.com/auto: "true"
  name: todelete
  labels:
    app: todelete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todelete
  template:
    metadata:
      name: todelete
      labels:
        app: todelete
    spec:
      volumes:
        - name: emptydirlogs
          emptyDir: {}
      containers:
        - name: microservice-pod 
          resources:
            requests:
              memory: 250Mi
              cpu : 200m
            limits:
              memory: 750Mi
              cpu : 500m
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8080
              scheme: HTTP
          env:
            - name: ocp-cluster.registry
              valueFrom:
                configMapKeyRef:
                  name: todelete-cm-0
                  key: ocp-cluster.registry
            - name: ocp.environment
              valueFrom:
                configMapKeyRef:
                  name: todelete-cm-0
                  key: ocp.environment
            - name: ocp-namespace
              valueFrom:
                configMapKeyRef:
                  name: todelete-cm-0
                  key: ocp-namespace
            - name: cluster-suffix
              valueFrom:
                configMapKeyRef:
                  name: todelete-cm-0
                  key: cluster-suffix
            - name: ocp.replicas
              valueFrom:
                configMapKeyRef:
                  name: todelete-cm-0
                  key: ocp.replicas
            - name: app-version
              valueFrom:
                configMapKeyRef:
                  name: todelete-cm-0
                  key: app-version
            - name: actuator.password
              valueFrom:
                secretKeyRef:
                  name: todelete-secret-0
                  key: actuator.password
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          imagePullPolicy: Always
          volumeMounts:
            - name: emptydirlogs
              mountPath: /Logs
          image: >-
            image-registry.openshift-image-registry.svc.cluster.local:5000/todelete-dev/todelete:0.0.1-SNAPSHOT
      restartPolicy: Always