kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: cambridge-dev
  annotations:
    its4u.placeholders/auto: "true"
    reloader.stakater.com/auto: "true"
  name: cambridge
  labels:
    app: cambridge
spec:
  replicas: {{ocp.replicas}}
  selector:
    matchLabels:
      app: cambridge
  template:
    metadata:
      name: cambridge
      labels:
        app: cambridge
    spec:
      volumes:
        - name: emptydirlogs
          emptyDir: {}
      containers:
        - name: microservice-pod 
          resources:
            requests:
              memory: 250Mi
              cpu : 200m
            limits:
              memory: 750Mi
              cpu : 500m
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8080
              scheme: HTTP
          env:
            - name: app-version
              valueFrom:
                configMapKeyRef:
                  name: cambridge-cm-0
                  key: app-version
            - name: cluster-suffix
              valueFrom:
                configMapKeyRef:
                  name: cambridge-cm-0
                  key: cluster-suffix
            - name: ocp.environment
              valueFrom:
                configMapKeyRef:
                  name: cambridge-cm-0
                  key: ocp.environment
            - name: ocp.replicas
              valueFrom:
                configMapKeyRef:
                  name: cambridge-cm-0
                  key: ocp.replicas
            - name: ocp-cluster.registry
              valueFrom:
                configMapKeyRef:
                  name: cambridge-cm-0
                  key: ocp-cluster.registry
            - name: ocp-namespace
              valueFrom:
                configMapKeyRef:
                  name: cambridge-cm-0
                  key: ocp-namespace
            - name: actuator.password
              valueFrom:
                secretKeyRef:
                  name: cambridge-secret-0
                  key: actuator.password
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          imagePullPolicy: Always
          volumeMounts:
            - name: emptydirlogs
              mountPath: /Logs
          image: >-
            {{ocp-cluster.registry}}/{{ocp-namespace}}/cambridge:{{app-version}}
      restartPolicy: Always