kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: pusher-dev
  name: pusher-route
  labels:
    app: pusher
spec:
  to:
    kind: Service
    name: pusher-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
