kind: Service
apiVersion: v1
metadata:
  namespace: pusher-dev
  name: pusher-service
  labels:
    app: pusher
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pusher