kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: testjulien-dev
  annotations:
    its4u.placeholders/auto: "true"
    reloader.stakater.com/auto: "true"
  name: testjulien
  labels:
    app: testjulien
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testjulien
  template:
    metadata:
      name: testjulien
      labels:
        app: testjulien
    spec:
      volumes:
        - name: emptydirlogs
          emptyDir: {}
        - name: emptydir-vol-1
          emptyDir: {}
        - name: cm-cm-1-vol
          configMap:
            name: testjulien-cm-1
            items:
              - key: aml-integration-context.xml
                path: aml-integration-context.xml
            defaultMode: 420
      containers:
        - name: microservice-pod 
          resources:
            requests:
              memory: 250Mi
              cpu : 200m
            limits:
              memory: 750Mi
              cpu : 500m
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8080
              scheme: HTTP
          env:
            - name: app-actuator.port
              valueFrom:
                configMapKeyRef:
                  name: testjulien-cm-0
                  key: app-actuator.port
            - name: app-container.port
              valueFrom:
                configMapKeyRef:
                  name: testjulien-cm-0
                  key: app-container.port
            - name: app-limit.cpu
              valueFrom:
                configMapKeyRef:
                  name: testjulien-cm-0
                  key: app-limit.cpu
            - name: app-limit.memory
              valueFrom:
                configMapKeyRef:
                  name: testjulien-cm-0
                  key: app-limit.memory
            - name: app-request.cpu
              valueFrom:
                configMapKeyRef:
                  name: testjulien-cm-0
                  key: app-request.cpu
            - name: app-request.memory
              valueFrom:
                configMapKeyRef:
                  name: testjulien-cm-0
                  key: app-request.memory
            - name: app-version
              valueFrom:
                configMapKeyRef:
                  name: testjulien-cm-0
                  key: app-version
            - name: cluster-suffix
              valueFrom:
                configMapKeyRef:
                  name: testjulien-cm-0
                  key: cluster-suffix
            - name: ocp.environment
              valueFrom:
                configMapKeyRef:
                  name: testjulien-cm-0
                  key: ocp.environment
            - name: ocp.replicas
              valueFrom:
                configMapKeyRef:
                  name: testjulien-cm-0
                  key: ocp.replicas
            - name: ocp-cluster.registry
              valueFrom:
                configMapKeyRef:
                  name: testjulien-cm-0
                  key: ocp-cluster.registry
            - name: ocp-namespace
              valueFrom:
                configMapKeyRef:
                  name: testjulien-cm-0
                  key: ocp-namespace
            - name: actuator.password
              valueFrom:
                secretKeyRef:
                  name: testjulien-secret-0
                  key: actuator.password
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          imagePullPolicy: Always
          volumeMounts:
            - name: emptydirlogs
              mountPath: /Logs
            - name: emptydir-vol-1
              mountPath: config
            - name: cm-cm-1-vol
              mountPath: config/aml
          image: >-
            image-registry.openshift-image-registry.svc.cluster.local:5000/testjulien-dev/testjulien:0.0.1-SNAPSHOT
      restartPolicy: Always