kind: Service
apiVersion: v1
metadata:
  namespace: testjulien-dev
  name: testjulien-service
  labels:
    app: testjulien
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: testjulien