kind: Secret
apiVersion: v1
metadata:
  namespace: test-rose-dev
  name: test-rose-secret-0
  labels:
    app: test-rose    
stringData:  
  actuator.password: {{actuator.password}}
type: Opaque
---
 