kind: Secret
apiVersion: v1
metadata:
  namespace: {{ocp-namespace}}
  name: ksc-lab-secret-0
  labels:
    app: ksc-lab    
stringData:  
  actuator.password: {{actuator.password}}
type: Opaque
---
 