kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: test-new-tst
  name: test-new-route
  labels:
    app: test-new
spec:
  to:
    kind: Service
    name: test-new-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
