kind: Service
apiVersion: v1
metadata:
  namespace: test-new-tst
  name: test-new-service
  labels:
    app: test-new
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: test-new