apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: devops4u-trigger
  namespace: devops4u-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: devops4u
  template:
    ref: devops4u