kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: DEVOPS
  name: first-app-route
  labels:
    app: first-app
spec:
  to:
    kind: Service
    name: first-app-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
