apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: test-titi-trigger
  namespace: test-titi-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: test-titi
  template:
    ref: test-titi