kind: Service
apiVersion: v1
metadata:
  namespace: importer-dev
  name: importer-service
  labels:
    app: importer
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: importer